// <auto-generated />
using System;
using Kartverket.Web.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kartverket.Web.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250926090118_fjerne_navn_på_mapobject")]
    partial class fjerne_navn_på_mapobject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Kartverket.Web.Database.Tables.MapObjectTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("MapObjectTypeId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("MapObjectTypeId");

                    b.ToTable("MapObjects");
                });

            modelBuilder.Entity("Kartverket.Web.Database.Tables.MapObjectTypeTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MapObjectTypes");
                });

            modelBuilder.Entity("Kartverket.Web.Database.Tables.MapPointTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ASML")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<Guid>("MapObjectId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("MapObjectId");

                    b.HasIndex("ReportId");

                    b.ToTable("MapPoints");
                });

            modelBuilder.Entity("Kartverket.Web.Database.Tables.ReportFeedbackAssignmentTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ReportFeedbackId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ReportFeedbackId", "UserId")
                        .IsUnique();

                    b.ToTable("ReportFeedbackAssignments");
                });

            modelBuilder.Entity("Kartverket.Web.Database.Tables.ReportFeedbackTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportFeedbacks");
                });

            modelBuilder.Entity("Kartverket.Web.Database.Tables.ReportTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Kartverket.Web.Database.Tables.RoleTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Kartverket.Web.Database.Tables.UserTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Kartverket.Web.Database.Tables.MapObjectTable", b =>
                {
                    b.HasOne("Kartverket.Web.Database.Tables.MapObjectTypeTable", "MapObjectType")
                        .WithMany("MapObjects")
                        .HasForeignKey("MapObjectTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MapObjectType");
                });

            modelBuilder.Entity("Kartverket.Web.Database.Tables.MapPointTable", b =>
                {
                    b.HasOne("Kartverket.Web.Database.Tables.MapObjectTable", "MapObject")
                        .WithMany("MapPoints")
                        .HasForeignKey("MapObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kartverket.Web.Database.Tables.ReportTable", "Report")
                        .WithMany("MapPoints")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MapObject");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Kartverket.Web.Database.Tables.ReportFeedbackAssignmentTable", b =>
                {
                    b.HasOne("Kartverket.Web.Database.Tables.ReportFeedbackTable", "ReportFeedback")
                        .WithMany()
                        .HasForeignKey("ReportFeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kartverket.Web.Database.Tables.UserTable", "User")
                        .WithMany("ReportFeedbackAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportFeedback");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kartverket.Web.Database.Tables.ReportFeedbackTable", b =>
                {
                    b.HasOne("Kartverket.Web.Database.Tables.ReportTable", "Report")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Kartverket.Web.Database.Tables.ReportTable", b =>
                {
                    b.HasOne("Kartverket.Web.Database.Tables.UserTable", "User")
                        .WithMany("Reports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kartverket.Web.Database.Tables.UserTable", b =>
                {
                    b.HasOne("Kartverket.Web.Database.Tables.RoleTable", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Kartverket.Web.Database.Tables.MapObjectTable", b =>
                {
                    b.Navigation("MapPoints");
                });

            modelBuilder.Entity("Kartverket.Web.Database.Tables.MapObjectTypeTable", b =>
                {
                    b.Navigation("MapObjects");
                });

            modelBuilder.Entity("Kartverket.Web.Database.Tables.ReportTable", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("MapPoints");
                });

            modelBuilder.Entity("Kartverket.Web.Database.Tables.RoleTable", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Kartverket.Web.Database.Tables.UserTable", b =>
                {
                    b.Navigation("ReportFeedbackAssignments");

                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
